### ISSUE TITLE
Plugins Enable Error

### ISSUE THREAD

**Issue by swan201** [BeYkeRYkt/ProtocolSupportVersionControl#4]
Something wrong?

[21:15:08] [Server thread/INFO]: [ProtocolSupportVersionControl] Enabling ProtocolSupportVersionControl v1.0.3
[21:15:08] [Server thread/INFO]: [ProtocolSupportVersionControl] Cannot load protocol version: 51. Reason: Unknown protocol version
[21:15:08] [Server thread/ERROR]: Error occurred while enabling ProtocolSupportVersionControl v1.0.3 (Is it up to date?)
java.lang.IllegalArgumentException: UNKNOWN is not a valid protocol version
    at protocolsupport.api.remapper.ItemRemapperControl.<init>(ItemRemapperControl.java:20) ~[?:?]
    at protocolsupport.api.ProtocolSupportAPI.getItemRemapper(ProtocolSupportAPI.java:22) ~[?:?]
    at ru.BeYkeRYkt.ProtocolSupportVersionControl.ProtocolSupportVersionControl.loadItemReplace(ProtocolSupportVersionControl.java:231) ~[?:?]
    at ru.BeYkeRYkt.ProtocolSupportVersionControl.ProtocolSupportVersionControl.onEnable(ProtocolSupportVersionControl.java:119) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by BeYkeRYkt** [comment]
ProtocolSupport version ?

**Comment by swan201** [comment]
@BeYkeRYkt I use #288 and Lastest Spigot.

**Comment by BeYkeRYkt** [comment]
@swan201 You can use latest dev version ProtocolSupport or delete line "51" from config

**Comment by swan201** [comment]
@BeYkeRYkt I used Latest Dev version ProtocolSupporot, But Still have enable Error ;.; and i delete that 51 source code but plugins have another error

**Comment by BeYkeRYkt** [comment]
@swan201 I used the latest version ProtocolSupport, but I have not found error. Are you sure using latest version of plugins?

**Comment by swan201** [comment]
@BeYkeRYkt I reinstall Eclipse and Rebuild Plugins. Is work! Thx
